export type Resource = {
  id: string;
  name: string;
  category:
    | "Software"
    | "DSA"
    | "Full-Stack"
    | "Cloud"
    | "Security"
    | "DevOps"
    | "AI/ML"
    | "AI APIs"
    | "AI Automation"
    | "AI Coding"
    | "Interview Prep";
  type: "Course" | "Docs" | "Video" | "Practice" | "Lab" | "Blog";
  bestFor: string;
  week: string;
  time: string;
  url: string;
  howToUse: string;
  firstStep: string;
  skip: string;
};

const r = (
  id: string,
  name: string,
  category: Resource["category"],
  type: Resource["type"],
  bestFor: string,
  week: string,
  time: string,
  url = "",
  howToUse = "Spend 20–40 min, then build a tiny output and commit it.",
  firstStep = "Open the intro page and finish the first lesson.",
  skip = "Optional advanced sections in early weeks.",
): Resource => ({ id, name, category, type, bestFor, week, time, url, howToUse, firstStep, skip });

export const RESOURCES: Resource[] = [
  // Software
  r(
    "cs50p",
    "CS50P (Harvard)",
    "Software",
    "Course",
    "Beginner Python",
    "Week 1–2",
    "20h",
    "https://cs50.harvard.edu/python/",
  ),
  r(
    "fcc-py",
    "freeCodeCamp Python",
    "Software",
    "Video",
    "Python crash",
    "Week 1",
    "5h",
    "https://www.freecodecamp.org/",
  ),
  r(
    "w3-py",
    "W3Schools Python",
    "Software",
    "Docs",
    "Syntax reference",
    "Week 1",
    "ref",
    "https://www.w3schools.com/python/",
  ),
  r(
    "programiz",
    "Programiz Python",
    "Software",
    "Docs",
    "Beginner tutorials",
    "Week 1",
    "ref",
    "https://www.programiz.com/python-programming",
  ),
  r(
    "realpy",
    "Real Python",
    "Software",
    "Blog",
    "Practical Python",
    "Week 1–2",
    "ref",
    "https://realpython.com/",
  ),
  r(
    "exercism",
    "Exercism Python",
    "Software",
    "Practice",
    "Exercises + mentor feedback",
    "Week 1–2",
    "1h/day",
    "https://exercism.org/tracks/python",
  ),
  r(
    "hr-py",
    "HackerRank Python",
    "Software",
    "Practice",
    "Practice problems",
    "Week 1–2",
    "1h/day",
    "https://www.hackerrank.com/domains/python",
  ),
  // DSA
  r(
    "neetcode",
    "NeetCode",
    "DSA",
    "Video",
    "Pattern-based DSA",
    "Week 1–11",
    "30–45min/day",
    "https://neetcode.io/",
  ),
  r(
    "takeuforward",
    "takeUforward",
    "DSA",
    "Video",
    "Striver SDE sheet",
    "Week 2+",
    "30min/day",
    "https://takeuforward.org/",
  ),
  r(
    "visualgo",
    "Visualgo",
    "DSA",
    "Practice",
    "Visual algorithms",
    "Week 2+",
    "ref",
    "https://visualgo.net/",
  ),
  r(
    "leetcode",
    "LeetCode",
    "DSA",
    "Practice",
    "Daily problems",
    "Week 2+",
    "30–45min/day",
    "https://leetcode.com/",
  ),
  r(
    "gfg-dsa",
    "GeeksforGeeks DSA",
    "DSA",
    "Docs",
    "Concept articles",
    "Week 2+",
    "ref",
    "https://www.geeksforgeeks.org/data-structures/",
  ),
  // Full-stack
  r(
    "odin",
    "The Odin Project",
    "Full-Stack",
    "Course",
    "Full-stack path",
    "Week 3–5",
    "long",
    "https://www.theodinproject.com/",
  ),
  r(
    "mdn",
    "MDN Web Docs",
    "Full-Stack",
    "Docs",
    "Web reference",
    "Week 3+",
    "ref",
    "https://developer.mozilla.org/",
  ),
  r(
    "jsinfo",
    "JavaScript.info",
    "Full-Stack",
    "Docs",
    "JS deep dive",
    "Week 3",
    "10h",
    "https://javascript.info/",
  ),
  r(
    "fem",
    "Frontend Mentor",
    "Full-Stack",
    "Practice",
    "UI build challenges",
    "Week 3–4",
    "1–3h/challenge",
    "https://www.frontendmentor.io/",
  ),
  r(
    "react",
    "React Official Docs",
    "Full-Stack",
    "Docs",
    "React 19",
    "Week 4",
    "ref",
    "https://react.dev/",
  ),
  r(
    "node",
    "Node.js Docs",
    "Full-Stack",
    "Docs",
    "Node API",
    "Week 5",
    "ref",
    "https://nodejs.org/en/docs",
  ),
  r(
    "express",
    "Express Docs",
    "Full-Stack",
    "Docs",
    "REST APIs",
    "Week 5",
    "ref",
    "https://expressjs.com/",
  ),
  r(
    "fastapi",
    "FastAPI Docs",
    "Full-Stack",
    "Docs",
    "Python APIs",
    "Week 5",
    "ref",
    "https://fastapi.tiangolo.com/",
  ),
  r(
    "sqlbolt",
    "SQLBolt",
    "Full-Stack",
    "Practice",
    "SQL basics",
    "Week 5",
    "3h",
    "https://sqlbolt.com/",
  ),
  r(
    "pg",
    "PostgreSQL Docs",
    "Full-Stack",
    "Docs",
    "Relational DB",
    "Week 5",
    "ref",
    "https://www.postgresql.org/docs/",
  ),
  r(
    "postman",
    "Postman Learning Center",
    "Full-Stack",
    "Docs",
    "API testing",
    "Week 5",
    "ref",
    "https://learning.postman.com/",
  ),
  // Cloud
  r(
    "aws-skill",
    "AWS Skill Builder",
    "Cloud",
    "Course",
    "AWS courses",
    "Week 6–7",
    "long",
    "https://skillbuilder.aws/",
  ),
  r(
    "aws-cp",
    "AWS Cloud Practitioner Essentials",
    "Cloud",
    "Course",
    "Cloud foundations",
    "Week 7",
    "6h",
    "https://aws.amazon.com/training/",
  ),
  r(
    "aws-ws",
    "AWS Workshops",
    "Cloud",
    "Lab",
    "Hands-on labs",
    "Week 7",
    "1–3h each",
    "https://workshops.aws/",
  ),
  r(
    "aws-docs",
    "AWS Docs",
    "Cloud",
    "Docs",
    "Service reference",
    "Week 7+",
    "ref",
    "https://docs.aws.amazon.com/",
  ),
  r(
    "crc",
    "Cloud Resume Challenge",
    "Cloud",
    "Lab",
    "End-to-end deploy",
    "Week 7",
    "1 week",
    "https://cloudresumechallenge.dev/",
  ),
  // Security
  r(
    "psw",
    "PortSwigger Web Security Academy",
    "Security",
    "Lab",
    "AppSec labs",
    "Week 9",
    "long",
    "https://portswigger.net/web-security",
  ),
  r("owasp", "OWASP", "Security", "Docs", "Top 10", "Week 9", "ref", "https://owasp.org/"),
  r(
    "juice",
    "OWASP Juice Shop",
    "Security",
    "Lab",
    "Vulnerable app",
    "Week 9",
    "few hrs",
    "https://owasp.org/www-project-juice-shop/",
  ),
  r(
    "thm",
    "TryHackMe Pre-Security",
    "Security",
    "Course",
    "Beginner sec",
    "Week 9",
    "5h",
    "https://tryhackme.com/",
  ),
  r(
    "htb",
    "HackTheBox Academy",
    "Security",
    "Course",
    "Beginner modules",
    "Week 9",
    "long",
    "https://academy.hackthebox.com/",
  ),
  r(
    "messer",
    "Professor Messer Security+",
    "Security",
    "Video",
    "Sec+ basics",
    "Week 9",
    "long",
    "https://www.professormesser.com/",
  ),
  // DevOps
  r(
    "docker-docs",
    "Docker Docs",
    "DevOps",
    "Docs",
    "Containers",
    "Week 8",
    "ref",
    "https://docs.docker.com/",
  ),
  r(
    "pwd",
    "Play with Docker",
    "DevOps",
    "Lab",
    "Browser docker",
    "Week 8",
    "1h",
    "https://labs.play-with-docker.com/",
  ),
  r(
    "gha",
    "GitHub Actions Docs",
    "DevOps",
    "Docs",
    "CI basics",
    "Week 8",
    "ref",
    "https://docs.github.com/actions",
  ),
  r(
    "kodekloud",
    "KodeKloud",
    "DevOps",
    "Course",
    "DevOps labs",
    "Week 8",
    "long",
    "https://kodekloud.com/",
  ),
  // AI/ML
  r(
    "gml",
    "Google ML Crash Course",
    "AI/ML",
    "Course",
    "ML intro",
    "Week 10",
    "10h",
    "https://developers.google.com/machine-learning/crash-course",
  ),
  r(
    "kaggle",
    "Kaggle Learn",
    "AI/ML",
    "Course",
    "Hands-on",
    "Week 10",
    "long",
    "https://www.kaggle.com/learn",
  ),
  r(
    "tm",
    "Teachable Machine",
    "AI/ML",
    "Lab",
    "No-code intro",
    "Week 10",
    "1h",
    "https://teachablemachine.withgoogle.com/",
  ),
  r(
    "fastai",
    "fast.ai",
    "AI/ML",
    "Course",
    "Deep learning",
    "Week 10+",
    "long",
    "https://www.fast.ai/",
  ),
  r(
    "fcc-ml",
    "freeCodeCamp ML w/ Python",
    "AI/ML",
    "Video",
    "ML intro",
    "Week 10",
    "10h",
    "https://www.freecodecamp.org/",
  ),
  r(
    "hf-learn",
    "Hugging Face Learn",
    "AI/ML",
    "Course",
    "Transformers",
    "Week 10–11",
    "long",
    "https://huggingface.co/learn",
  ),
  r(
    "dlai",
    "DeepLearning.AI",
    "AI/ML",
    "Course",
    "Foundations",
    "Week 10+",
    "long",
    "https://www.deeplearning.ai/",
  ),
  // AI APIs
  r(
    "openai",
    "OpenAI API Docs",
    "AI APIs",
    "Docs",
    "LLM APIs",
    "Week 11",
    "ref",
    "https://platform.openai.com/docs",
  ),
  r(
    "claude-api",
    "Claude API Docs",
    "AI APIs",
    "Docs",
    "Claude APIs",
    "Week 11",
    "ref",
    "https://docs.anthropic.com/",
  ),
  r(
    "hf-api",
    "Hugging Face API Docs",
    "AI APIs",
    "Docs",
    "Open models",
    "Week 11",
    "ref",
    "https://huggingface.co/docs",
  ),
  r(
    "langchain",
    "LangChain Docs",
    "AI APIs",
    "Docs",
    "AI orchestration",
    "Week 11+",
    "ref",
    "https://python.langchain.com/",
  ),
  r(
    "llamaindex",
    "LlamaIndex Docs",
    "AI APIs",
    "Docs",
    "RAG",
    "Week 11+",
    "ref",
    "https://docs.llamaindex.ai/",
  ),
  r(
    "pinecone",
    "Pinecone Learn",
    "AI APIs",
    "Docs",
    "Vector DB",
    "Week 11+",
    "ref",
    "https://www.pinecone.io/learn/",
  ),
  // Automation
  r(
    "n8n",
    "n8n Docs",
    "AI Automation",
    "Docs",
    "Workflows",
    "Week 12",
    "ref",
    "https://docs.n8n.io/",
  ),
  r(
    "n8n-ai",
    "n8n AI Agent Docs",
    "AI Automation",
    "Docs",
    "AI agents",
    "Week 12",
    "ref",
    "https://docs.n8n.io/advanced-ai/",
  ),
  r(
    "make",
    "Make Academy",
    "AI Automation",
    "Course",
    "No-code automation",
    "Week 12",
    "few hrs",
    "https://academy.make.com/",
  ),
  r(
    "zapier",
    "Zapier Learn",
    "AI Automation",
    "Course",
    "Zaps",
    "Week 12",
    "few hrs",
    "https://zapier.com/learn",
  ),
  r(
    "apps-script",
    "Google Apps Script Docs",
    "AI Automation",
    "Docs",
    "Sheets automation",
    "Week 12",
    "ref",
    "https://developers.google.com/apps-script",
  ),
  r(
    "hf-agents",
    "Hugging Face Agents Course",
    "AI Automation",
    "Course",
    "Agentic AI",
    "Week 12",
    "few hrs",
    "https://huggingface.co/learn/agents-course",
  ),
  // AI Coding
  r(
    "claude-code",
    "Claude Code Docs",
    "AI Coding",
    "Docs",
    "Multi-file coding",
    "All weeks",
    "ref",
    "https://docs.anthropic.com/",
  ),
  r(
    "cursor",
    "Cursor Docs",
    "AI Coding",
    "Docs",
    "IDE",
    "All weeks",
    "ref",
    "https://docs.cursor.com/",
  ),
  r(
    "copilot",
    "GitHub Copilot Docs",
    "AI Coding",
    "Docs",
    "Autocomplete",
    "All weeks",
    "ref",
    "https://docs.github.com/copilot",
  ),
  r(
    "chatgpt",
    "ChatGPT",
    "AI Coding",
    "Docs",
    "Tutor + helper",
    "All weeks",
    "ref",
    "https://chat.openai.com/",
  ),
  r(
    "continue",
    "Continue.dev",
    "AI Coding",
    "Docs",
    "OSS coding agent",
    "All weeks",
    "ref",
    "https://www.continue.dev/",
  ),
  r(
    "lovable",
    "Lovable",
    "AI Coding",
    "Docs",
    "AI app builder",
    "All weeks",
    "ref",
    "https://lovable.dev/",
  ),
  r(
    "v0",
    "v0 by Vercel",
    "AI Coding",
    "Docs",
    "AI UI generator",
    "All weeks",
    "ref",
    "https://v0.dev/",
  ),
];
