export type Tool = {
  name: string;
  category: "AI" | "Software" | "Cloud" | "Security" | "AI/Automation";
  what: string;
  why: string;
  when: string;
  weeks: string;
  setup: string;
  tip: string;
  mistake: string;
  safety: string;
  url: string;
};

const t = (
  name: string,
  category: Tool["category"],
  what: string,
  why: string,
  when: string,
  weeks: string,
  setup: string,
  tip: string,
  mistake: string,
  safety: string,
  url = "",
): Tool => ({ name, category, what, why, when, weeks, setup, tip, mistake, safety, url });

export const TOOLS: Tool[] = [
  // AI
  t(
    "ChatGPT",
    "AI",
    "General LLM chatbot",
    "Beginner explanations + quizzes",
    "Daily concept breakdown, debug help, interview prep",
    "All",
    "Sign in at chat.openai.com",
    "Ask for tiny example + task + mistake to avoid",
    "Asking for full project code",
    "Never paste API keys or secrets",
    "https://chat.openai.com",
  ),
  t(
    "Claude",
    "AI",
    "Long-context LLM by Anthropic",
    "Deep reasoning, code review, architecture",
    "Project review, README, security review",
    "All",
    "Use claude.ai",
    "Paste files + ask for safe step-by-step plan",
    "Letting Claude rewrite without review",
    "Avoid pasting prod secrets",
    "https://claude.ai",
  ),
  t(
    "Claude Code",
    "AI",
    "Multi-file CLI coding agent",
    "Multi-file refactors, tests, README",
    "Project-wide changes",
    "Week 7+",
    "Install CLI per docs",
    "Always require approval before file changes",
    "Auto-accepting destructive edits",
    "Run inside repo only",
    "https://docs.anthropic.com",
  ),
  t(
    "Cursor",
    "AI",
    "AI-first VS Code fork",
    "Inline edits with project context",
    "Components, routes, refactors",
    "Week 3+",
    "Download cursor.com",
    "Use chat with selected file scope",
    "Accepting suggestions without reading",
    "Disable telemetry for private code",
    "https://cursor.com",
  ),
  t(
    "GitHub Copilot",
    "AI",
    "Inline autocomplete",
    "Speed up boilerplate",
    "Tests, helpers, repeated code",
    "All",
    "Install VS Code extension",
    "Review every suggestion",
    "Treating it as truth",
    "Do not commit unreviewed code",
    "https://github.com/features/copilot",
  ),
  t(
    "v0 by Vercel",
    "AI",
    "AI UI generator",
    "Quick React + Tailwind UI drafts",
    "When mocking UI ideas",
    "Week 3+",
    "v0.dev",
    "Refine prompts iteratively",
    "Shipping AI UI without a11y pass",
    "Audit dependencies it adds",
    "https://v0.dev",
  ),
  t(
    "Lovable",
    "AI",
    "AI app builder",
    "Build full apps with chat",
    "Prototyping ideas",
    "All",
    "lovable.dev",
    "Iterate in small, scoped changes",
    "Asking for huge changes at once",
    "Review backend code carefully",
    "https://lovable.dev",
  ),
  // Software
  t(
    "Python",
    "Software",
    "Programming language",
    "Easy syntax, huge ecosystem",
    "Scripts, ML, APIs",
    "Week 1+",
    "Install Python 3 + pip",
    "Use venv per project",
    "Polluting global Python",
    "Pin requirements.txt",
    "https://python.org",
  ),
  t(
    "VS Code",
    "Software",
    "Code editor",
    "Free, extensible",
    "Daily coding",
    "All",
    "code.visualstudio.com",
    "Use workspace settings per project",
    "Installing too many extensions",
    "Audit extensions before installing",
    "https://code.visualstudio.com",
  ),
  t(
    "Git",
    "Software",
    "Version control",
    "Track changes",
    "Every commit",
    "All",
    "Install git",
    "Make small, named commits",
    "Force-pushing main",
    "Never commit .env",
    "https://git-scm.com",
  ),
  t(
    "GitHub",
    "Software",
    "Code hosting",
    "Portfolio & collaboration",
    "All projects",
    "All",
    "github.com",
    "Push daily, README every repo",
    "Empty repos with no README",
    "Use SSH keys + 2FA",
    "https://github.com",
  ),
  t(
    "Node.js",
    "Software",
    "JS runtime",
    "Backend JS",
    "Week 5+",
    "nodejs.org",
    "Use LTS version + nvm",
    "Mismatched Node versions",
    "Audit dependencies",
    "https://nodejs.org",
  ),
  t(
    "React",
    "Software",
    "UI library",
    "Modern component UI",
    "Week 4+",
    "Use Vite template",
    "Keep components small",
    "Prop drilling everything",
    "Sanitize user-rendered HTML",
    "https://react.dev",
  ),
  t(
    "FastAPI",
    "Software",
    "Python web framework",
    "Typed Python APIs",
    "Week 5+",
    "pip install fastapi",
    "Use Pydantic models",
    "Skipping input validation",
    "Validate every input",
    "https://fastapi.tiangolo.com",
  ),
  t(
    "Express",
    "Software",
    "Node web framework",
    "Quick REST APIs",
    "Week 5+",
    "npm i express",
    "Use middleware for auth",
    "Mixing routes + logic",
    "Never trust req.body",
    "https://expressjs.com",
  ),
  t(
    "PostgreSQL",
    "Software",
    "Relational DB",
    "Solid, free SQL DB",
    "Week 5+",
    "Install postgres or use Docker",
    "Use migrations",
    "Shipping schema without migrations",
    "Use parameterized queries",
    "https://postgresql.org",
  ),
  t(
    "Postman",
    "Software",
    "API client",
    "Test APIs",
    "Week 5+",
    "postman.com",
    "Save collections per project",
    "Storing tokens in plain text",
    "Use environment vaults",
    "https://postman.com",
  ),
  t(
    "Docker",
    "Software",
    "Containers",
    "Reproducible envs",
    "Week 8+",
    "docker.com",
    "Use multi-stage builds",
    "Huge image sizes",
    "Don't bake secrets into images",
    "https://docker.com",
  ),
  t(
    "AWS CLI",
    "Cloud",
    "AWS command line",
    "Automate AWS",
    "Week 7+",
    "aws configure",
    "Use named profiles",
    "Using root account",
    "Use IAM least-privilege",
    "https://aws.amazon.com/cli/",
  ),
  // Cloud
  t(
    "AWS Console",
    "Cloud",
    "AWS web UI",
    "Browse services",
    "Week 7+",
    "aws.amazon.com",
    "Set billing alerts day 1",
    "Leaving EC2 on",
    "Enable MFA on root",
    "https://aws.amazon.com",
  ),
  t(
    "IAM",
    "Cloud",
    "Identity & access",
    "Permissions",
    "Week 7",
    "Create non-root user",
    "Use roles, not keys",
    "Over-permissive policies",
    "Least privilege always",
    "",
  ),
  t(
    "EC2",
    "Cloud",
    "Virtual servers",
    "Run apps",
    "Week 7",
    "Launch t2.micro",
    "Stop when not used",
    "Open ports to 0.0.0.0/0",
    "Restrict security groups",
    "",
  ),
  t(
    "S3",
    "Cloud",
    "Object storage",
    "Files + static sites",
    "Week 7",
    "Create bucket",
    "Enable versioning",
    "Public buckets by accident",
    "Block public access by default",
    "",
  ),
  t(
    "CloudWatch",
    "Cloud",
    "Logs + alarms",
    "Monitor apps",
    "Week 7",
    "Enable per resource",
    "Set 1 alarm for cost + 1 for errors",
    "Ignoring alerts",
    "Encrypt log groups",
    "",
  ),
  t(
    "RDS",
    "Cloud",
    "Managed DB",
    "Postgres in cloud",
    "Week 7",
    "Create db.t3.micro",
    "Disable public access",
    "Public RDS endpoints",
    "Use secrets manager",
    "",
  ),
  t(
    "Lambda",
    "Cloud",
    "Serverless functions",
    "Event-driven code",
    "Week 7",
    "Create function",
    "Keep handlers tiny",
    "Cold-start heavy work",
    "Pin dependencies",
    "",
  ),
  // Security
  t(
    "Burp Suite",
    "Security",
    "Web proxy",
    "Inspect requests",
    "Week 9",
    "Install community ed.",
    "Use only on your own apps",
    "Testing prod without permission",
    "Legal labs only",
    "https://portswigger.net/burp",
  ),
  t(
    "OWASP ZAP",
    "Security",
    "Open-source web scanner",
    "Scan your APIs",
    "Week 9",
    "Install ZAP",
    "Run baseline scan",
    "Treating scan as proof of secure",
    "Manual review needed",
    "https://www.zaproxy.org/",
  ),
  t(
    "Wireshark",
    "Security",
    "Packet analyzer",
    "See network traffic",
    "Week 6",
    "Install Wireshark",
    "Capture on lab Wi-Fi only",
    "Capturing on networks you don't own",
    "Legal scope only",
    "https://www.wireshark.org/",
  ),
  t(
    "TryHackMe",
    "Security",
    "Beginner sec labs",
    "Hands-on learning",
    "Week 9",
    "tryhackme.com",
    "Start Pre-Security path",
    "Skipping notes",
    "Stay inside platform",
    "https://tryhackme.com",
  ),
  t(
    "OWASP Juice Shop",
    "Security",
    "Vulnerable app",
    "Practice OWASP Top 10",
    "Week 9",
    "Docker run",
    "Run locally, document fixes",
    "Hosting it publicly",
    "Local only",
    "https://owasp.org/www-project-juice-shop/",
  ),
  // AI/Automation
  t(
    "Google Colab",
    "AI/Automation",
    "Cloud notebooks",
    "Free GPU for ML",
    "Week 10+",
    "colab.google",
    "Restart runtime when stuck",
    "Leaving GPUs idle",
    "Don't upload secrets",
    "https://colab.google",
  ),
  t(
    "Kaggle",
    "AI/Automation",
    "Datasets + notebooks",
    "Practice ML",
    "Week 10+",
    "kaggle.com",
    "Fork beginner notebooks",
    "Just copying notebooks",
    "Respect dataset licenses",
    "https://kaggle.com",
  ),
  t(
    "Hugging Face",
    "AI/Automation",
    "Open AI hub",
    "Models + datasets",
    "Week 10+",
    "huggingface.co",
    "Use Inference API for tests",
    "Downloading huge models locally",
    "Check model license",
    "https://huggingface.co",
  ),
  t(
    "OpenAI API",
    "AI/Automation",
    "Hosted LLM API",
    "AI features in apps",
    "Week 11+",
    "platform.openai.com",
    "Keep keys in .env on server",
    "Calling from client with key",
    "Server-side only",
    "https://platform.openai.com",
  ),
  t(
    "Claude API",
    "AI/Automation",
    "Anthropic LLM API",
    "Long context AI",
    "Week 11+",
    "console.anthropic.com",
    "Same .env safety as OpenAI",
    "Logging full prompts with PII",
    "Mask PII",
    "https://console.anthropic.com",
  ),
  t(
    "n8n",
    "AI/Automation",
    "Open-source automation",
    "Workflows + AI agents",
    "Week 12",
    "n8n.io / Docker",
    "Start with HTTP trigger + AI node",
    "Building giant flows up front",
    "Self-host securely",
    "https://n8n.io",
  ),
  t(
    "Make",
    "AI/Automation",
    "No-code automation",
    "Visual scenarios",
    "Week 12",
    "make.com",
    "Use webhooks as triggers",
    "Polling instead of webhooks",
    "Mask sensitive variables",
    "https://make.com",
  ),
  t(
    "Zapier",
    "AI/Automation",
    "No-code automation",
    "Pre-built apps",
    "Week 12",
    "zapier.com",
    "Use filters early",
    "Building runaway Zaps",
    "Audit shared accounts",
    "https://zapier.com",
  ),
  t(
    "Google Sheets",
    "AI/Automation",
    "Spreadsheet + Apps Script",
    "Quick storage + dashboards",
    "Week 12",
    "sheets.google.com",
    "Use named ranges",
    "Hardcoding values",
    "Restrict sharing",
    "https://sheets.google.com",
  ),
  t(
    "Discord / Email Webhooks",
    "AI/Automation",
    "Notification channels",
    "Alerts from automations",
    "Week 12",
    "Create webhook URL",
    "One channel per event type",
    "Pasting webhook URLs publicly",
    "Treat URLs as secrets",
    "",
  ),
];
