/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WeeklyRouteImport } from './routes/weekly'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as TodayRouteImport } from './routes/today'
import { Route as SkillGapRouteImport } from './routes/skill-gap'
import { Route as SchemaPlannerRouteImport } from './routes/schema-planner'
import { Route as SafetyRouteImport } from './routes/safety'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as RevisionRouteImport } from './routes/revision'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as ReadinessRouteImport } from './routes/readiness'
import { Route as PromptsRouteImport } from './routes/prompts'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as InterviewRouteImport } from './routes/interview'
import { Route as FocusRouteImport } from './routes/focus'
import { Route as FlowsRouteImport } from './routes/flows'
import { Route as ExplainRouteImport } from './routes/explain'
import { Route as ChecklistRouteImport } from './routes/checklist'
import { Route as CheatsheetsRouteImport } from './routes/cheatsheets'
import { Route as ChallengesRouteImport } from './routes/challenges'
import { Route as CapstoneRouteImport } from './routes/capstone'
import { Route as BugsRouteImport } from './routes/bugs'
import { Route as BrandingRouteImport } from './routes/branding'
import { Route as AssessmentsRouteImport } from './routes/assessments'
import { Route as ArchitectureRouteImport } from './routes/architecture'
import { Route as ApiPlannerRouteImport } from './routes/api-planner'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicErrorsRouteImport } from './routes/api/public/errors'

const WeeklyRoute = WeeklyRouteImport.update({
  id: '/weekly',
  path: '/weekly',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const TodayRoute = TodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillGapRoute = SkillGapRouteImport.update({
  id: '/skill-gap',
  path: '/skill-gap',
  getParentRoute: () => rootRouteImport,
} as any)
const SchemaPlannerRoute = SchemaPlannerRouteImport.update({
  id: '/schema-planner',
  path: '/schema-planner',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyRoute = SafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const RevisionRoute = RevisionRouteImport.update({
  id: '/revision',
  path: '/revision',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadinessRoute = ReadinessRouteImport.update({
  id: '/readiness',
  path: '/readiness',
  getParentRoute: () => rootRouteImport,
} as any)
const PromptsRoute = PromptsRouteImport.update({
  id: '/prompts',
  path: '/prompts',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewRoute = InterviewRouteImport.update({
  id: '/interview',
  path: '/interview',
  getParentRoute: () => rootRouteImport,
} as any)
const FocusRoute = FocusRouteImport.update({
  id: '/focus',
  path: '/focus',
  getParentRoute: () => rootRouteImport,
} as any)
const FlowsRoute = FlowsRouteImport.update({
  id: '/flows',
  path: '/flows',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplainRoute = ExplainRouteImport.update({
  id: '/explain',
  path: '/explain',
  getParentRoute: () => rootRouteImport,
} as any)
const ChecklistRoute = ChecklistRouteImport.update({
  id: '/checklist',
  path: '/checklist',
  getParentRoute: () => rootRouteImport,
} as any)
const CheatsheetsRoute = CheatsheetsRouteImport.update({
  id: '/cheatsheets',
  path: '/cheatsheets',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengesRoute = ChallengesRouteImport.update({
  id: '/challenges',
  path: '/challenges',
  getParentRoute: () => rootRouteImport,
} as any)
const CapstoneRoute = CapstoneRouteImport.update({
  id: '/capstone',
  path: '/capstone',
  getParentRoute: () => rootRouteImport,
} as any)
const BugsRoute = BugsRouteImport.update({
  id: '/bugs',
  path: '/bugs',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandingRoute = BrandingRouteImport.update({
  id: '/branding',
  path: '/branding',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentsRoute = AssessmentsRouteImport.update({
  id: '/assessments',
  path: '/assessments',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitectureRoute = ArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlannerRoute = ApiPlannerRouteImport.update({
  id: '/api-planner',
  path: '/api-planner',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicErrorsRoute = ApiPublicErrorsRouteImport.update({
  id: '/api/public/errors',
  path: '/api/public/errors',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api-planner': typeof ApiPlannerRoute
  '/architecture': typeof ArchitectureRoute
  '/assessments': typeof AssessmentsRoute
  '/branding': typeof BrandingRoute
  '/bugs': typeof BugsRoute
  '/capstone': typeof CapstoneRoute
  '/challenges': typeof ChallengesRoute
  '/cheatsheets': typeof CheatsheetsRoute
  '/checklist': typeof ChecklistRoute
  '/explain': typeof ExplainRoute
  '/flows': typeof FlowsRoute
  '/focus': typeof FocusRoute
  '/interview': typeof InterviewRoute
  '/jobs': typeof JobsRoute
  '/notes': typeof NotesRoute
  '/projects': typeof ProjectsRoute
  '/prompts': typeof PromptsRoute
  '/readiness': typeof ReadinessRoute
  '/resources': typeof ResourcesRoute
  '/revision': typeof RevisionRoute
  '/roadmap': typeof RoadmapRoute
  '/safety': typeof SafetyRoute
  '/schema-planner': typeof SchemaPlannerRoute
  '/skill-gap': typeof SkillGapRoute
  '/today': typeof TodayRoute
  '/tools': typeof ToolsRoute
  '/weekly': typeof WeeklyRoute
  '/api/public/errors': typeof ApiPublicErrorsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api-planner': typeof ApiPlannerRoute
  '/architecture': typeof ArchitectureRoute
  '/assessments': typeof AssessmentsRoute
  '/branding': typeof BrandingRoute
  '/bugs': typeof BugsRoute
  '/capstone': typeof CapstoneRoute
  '/challenges': typeof ChallengesRoute
  '/cheatsheets': typeof CheatsheetsRoute
  '/checklist': typeof ChecklistRoute
  '/explain': typeof ExplainRoute
  '/flows': typeof FlowsRoute
  '/focus': typeof FocusRoute
  '/interview': typeof InterviewRoute
  '/jobs': typeof JobsRoute
  '/notes': typeof NotesRoute
  '/projects': typeof ProjectsRoute
  '/prompts': typeof PromptsRoute
  '/readiness': typeof ReadinessRoute
  '/resources': typeof ResourcesRoute
  '/revision': typeof RevisionRoute
  '/roadmap': typeof RoadmapRoute
  '/safety': typeof SafetyRoute
  '/schema-planner': typeof SchemaPlannerRoute
  '/skill-gap': typeof SkillGapRoute
  '/today': typeof TodayRoute
  '/tools': typeof ToolsRoute
  '/weekly': typeof WeeklyRoute
  '/api/public/errors': typeof ApiPublicErrorsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api-planner': typeof ApiPlannerRoute
  '/architecture': typeof ArchitectureRoute
  '/assessments': typeof AssessmentsRoute
  '/branding': typeof BrandingRoute
  '/bugs': typeof BugsRoute
  '/capstone': typeof CapstoneRoute
  '/challenges': typeof ChallengesRoute
  '/cheatsheets': typeof CheatsheetsRoute
  '/checklist': typeof ChecklistRoute
  '/explain': typeof ExplainRoute
  '/flows': typeof FlowsRoute
  '/focus': typeof FocusRoute
  '/interview': typeof InterviewRoute
  '/jobs': typeof JobsRoute
  '/notes': typeof NotesRoute
  '/projects': typeof ProjectsRoute
  '/prompts': typeof PromptsRoute
  '/readiness': typeof ReadinessRoute
  '/resources': typeof ResourcesRoute
  '/revision': typeof RevisionRoute
  '/roadmap': typeof RoadmapRoute
  '/safety': typeof SafetyRoute
  '/schema-planner': typeof SchemaPlannerRoute
  '/skill-gap': typeof SkillGapRoute
  '/today': typeof TodayRoute
  '/tools': typeof ToolsRoute
  '/weekly': typeof WeeklyRoute
  '/api/public/errors': typeof ApiPublicErrorsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api-planner'
    | '/architecture'
    | '/assessments'
    | '/branding'
    | '/bugs'
    | '/capstone'
    | '/challenges'
    | '/cheatsheets'
    | '/checklist'
    | '/explain'
    | '/flows'
    | '/focus'
    | '/interview'
    | '/jobs'
    | '/notes'
    | '/projects'
    | '/prompts'
    | '/readiness'
    | '/resources'
    | '/revision'
    | '/roadmap'
    | '/safety'
    | '/schema-planner'
    | '/skill-gap'
    | '/today'
    | '/tools'
    | '/weekly'
    | '/api/public/errors'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api-planner'
    | '/architecture'
    | '/assessments'
    | '/branding'
    | '/bugs'
    | '/capstone'
    | '/challenges'
    | '/cheatsheets'
    | '/checklist'
    | '/explain'
    | '/flows'
    | '/focus'
    | '/interview'
    | '/jobs'
    | '/notes'
    | '/projects'
    | '/prompts'
    | '/readiness'
    | '/resources'
    | '/revision'
    | '/roadmap'
    | '/safety'
    | '/schema-planner'
    | '/skill-gap'
    | '/today'
    | '/tools'
    | '/weekly'
    | '/api/public/errors'
  id:
    | '__root__'
    | '/'
    | '/api-planner'
    | '/architecture'
    | '/assessments'
    | '/branding'
    | '/bugs'
    | '/capstone'
    | '/challenges'
    | '/cheatsheets'
    | '/checklist'
    | '/explain'
    | '/flows'
    | '/focus'
    | '/interview'
    | '/jobs'
    | '/notes'
    | '/projects'
    | '/prompts'
    | '/readiness'
    | '/resources'
    | '/revision'
    | '/roadmap'
    | '/safety'
    | '/schema-planner'
    | '/skill-gap'
    | '/today'
    | '/tools'
    | '/weekly'
    | '/api/public/errors'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPlannerRoute: typeof ApiPlannerRoute
  ArchitectureRoute: typeof ArchitectureRoute
  AssessmentsRoute: typeof AssessmentsRoute
  BrandingRoute: typeof BrandingRoute
  BugsRoute: typeof BugsRoute
  CapstoneRoute: typeof CapstoneRoute
  ChallengesRoute: typeof ChallengesRoute
  CheatsheetsRoute: typeof CheatsheetsRoute
  ChecklistRoute: typeof ChecklistRoute
  ExplainRoute: typeof ExplainRoute
  FlowsRoute: typeof FlowsRoute
  FocusRoute: typeof FocusRoute
  InterviewRoute: typeof InterviewRoute
  JobsRoute: typeof JobsRoute
  NotesRoute: typeof NotesRoute
  ProjectsRoute: typeof ProjectsRoute
  PromptsRoute: typeof PromptsRoute
  ReadinessRoute: typeof ReadinessRoute
  ResourcesRoute: typeof ResourcesRoute
  RevisionRoute: typeof RevisionRoute
  RoadmapRoute: typeof RoadmapRoute
  SafetyRoute: typeof SafetyRoute
  SchemaPlannerRoute: typeof SchemaPlannerRoute
  SkillGapRoute: typeof SkillGapRoute
  TodayRoute: typeof TodayRoute
  ToolsRoute: typeof ToolsRoute
  WeeklyRoute: typeof WeeklyRoute
  ApiPublicErrorsRoute: typeof ApiPublicErrorsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/weekly': {
      id: '/weekly'
      path: '/weekly'
      fullPath: '/weekly'
      preLoaderRoute: typeof WeeklyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/today': {
      id: '/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof TodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skill-gap': {
      id: '/skill-gap'
      path: '/skill-gap'
      fullPath: '/skill-gap'
      preLoaderRoute: typeof SkillGapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schema-planner': {
      id: '/schema-planner'
      path: '/schema-planner'
      fullPath: '/schema-planner'
      preLoaderRoute: typeof SchemaPlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety': {
      id: '/safety'
      path: '/safety'
      fullPath: '/safety'
      preLoaderRoute: typeof SafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/revision': {
      id: '/revision'
      path: '/revision'
      fullPath: '/revision'
      preLoaderRoute: typeof RevisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/readiness': {
      id: '/readiness'
      path: '/readiness'
      fullPath: '/readiness'
      preLoaderRoute: typeof ReadinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompts': {
      id: '/prompts'
      path: '/prompts'
      fullPath: '/prompts'
      preLoaderRoute: typeof PromptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interview': {
      id: '/interview'
      path: '/interview'
      fullPath: '/interview'
      preLoaderRoute: typeof InterviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/focus': {
      id: '/focus'
      path: '/focus'
      fullPath: '/focus'
      preLoaderRoute: typeof FocusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flows': {
      id: '/flows'
      path: '/flows'
      fullPath: '/flows'
      preLoaderRoute: typeof FlowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explain': {
      id: '/explain'
      path: '/explain'
      fullPath: '/explain'
      preLoaderRoute: typeof ExplainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checklist': {
      id: '/checklist'
      path: '/checklist'
      fullPath: '/checklist'
      preLoaderRoute: typeof ChecklistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cheatsheets': {
      id: '/cheatsheets'
      path: '/cheatsheets'
      fullPath: '/cheatsheets'
      preLoaderRoute: typeof CheatsheetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenges': {
      id: '/challenges'
      path: '/challenges'
      fullPath: '/challenges'
      preLoaderRoute: typeof ChallengesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capstone': {
      id: '/capstone'
      path: '/capstone'
      fullPath: '/capstone'
      preLoaderRoute: typeof CapstoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bugs': {
      id: '/bugs'
      path: '/bugs'
      fullPath: '/bugs'
      preLoaderRoute: typeof BugsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branding': {
      id: '/branding'
      path: '/branding'
      fullPath: '/branding'
      preLoaderRoute: typeof BrandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessments': {
      id: '/assessments'
      path: '/assessments'
      fullPath: '/assessments'
      preLoaderRoute: typeof AssessmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architecture': {
      id: '/architecture'
      path: '/architecture'
      fullPath: '/architecture'
      preLoaderRoute: typeof ArchitectureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-planner': {
      id: '/api-planner'
      path: '/api-planner'
      fullPath: '/api-planner'
      preLoaderRoute: typeof ApiPlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/errors': {
      id: '/api/public/errors'
      path: '/api/public/errors'
      fullPath: '/api/public/errors'
      preLoaderRoute: typeof ApiPublicErrorsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPlannerRoute: ApiPlannerRoute,
  ArchitectureRoute: ArchitectureRoute,
  AssessmentsRoute: AssessmentsRoute,
  BrandingRoute: BrandingRoute,
  BugsRoute: BugsRoute,
  CapstoneRoute: CapstoneRoute,
  ChallengesRoute: ChallengesRoute,
  CheatsheetsRoute: CheatsheetsRoute,
  ChecklistRoute: ChecklistRoute,
  ExplainRoute: ExplainRoute,
  FlowsRoute: FlowsRoute,
  FocusRoute: FocusRoute,
  InterviewRoute: InterviewRoute,
  JobsRoute: JobsRoute,
  NotesRoute: NotesRoute,
  ProjectsRoute: ProjectsRoute,
  PromptsRoute: PromptsRoute,
  ReadinessRoute: ReadinessRoute,
  ResourcesRoute: ResourcesRoute,
  RevisionRoute: RevisionRoute,
  RoadmapRoute: RoadmapRoute,
  SafetyRoute: SafetyRoute,
  SchemaPlannerRoute: SchemaPlannerRoute,
  SkillGapRoute: SkillGapRoute,
  TodayRoute: TodayRoute,
  ToolsRoute: ToolsRoute,
  WeeklyRoute: WeeklyRoute,
  ApiPublicErrorsRoute: ApiPublicErrorsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
